### ISSUE TITLE
Task fails with abstract model with no table on db

### ISSUE THREAD

**Issue by julitrows** [soulfly/unique_validation_inspector#1]
Hello!

Thanks for releasing this gem, seems it's going to be useful for me :D

On a Rails 4.2.9 project I've got an abstract model with a couple of children models.

```
Class BaseUser < ActiveRecord::Base
  self.abstract_class = true
```

With a couple of uniqueness validations. The rake task identifies the uniqueness validations, but since the model doesn't have a table, the `.to_sym` conversion [here](https://github.com/soulfly/unique_validation_inspector/blob/master/lib/unique_validation_inspector.rb#L34) fails:

```
Model 'BaseUser':
rake aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
/Users/julio/.rvm/gems/ruby-2.3.4@rubicon/gems/unique_validation_inspector-0.1.1/lib/unique_validation_inspector.rb:34:in `defined_unique_indexes'
/Users/julio/.rvm/gems/ruby-2.3.4@rubicon/gems/unique_validation_inspector-0.1.1/lib/tasks/inspect_unique_validations.rake:17:in `block (3 levels) in <top (required)>'
# ... [REDACTED]
Tasks: TOP => inspect_unique_validations
(See full trace by running task with --trace)
```

I guess models without a table index should be skipped for the check, and/or (at least useful for my use case) notify the user to keep an eye out on creating indexes for the validated fields on the children models tables.

Thanks a lot :)

**Comment by soulfly** [comment]
Thanks @jantequera  for the feedback! 
I'm going to check it now

**Comment by soulfly** [comment]
Did some quick tests.
Probably we can check for **descendant.abstract_class?** and skip it.

When I print **descendant.validators** then it returns all the validations: own + from the ancestor class. 
So it's okay.

**Comment by soulfly** [comment]
@jantequera 
I fixed the issue in this commit https://github.com/soulfly/unique_validation_inspector/commit/065ce350b1e8e97f928aae7ed5145b9bb37cff31 

And also added more tests for it

So you can check now

**Comment by soulfly** [comment]
Pushed 0.1.2 version to RubyGems 
https://rubygems.org/gems/unique_validation_inspector

**Comment by julitrows** [comment]
Looks good to me 👍 !!!! :D
